services:
  node:
    build:
      context: node
    image: bpierrii/fullcycle-node
    container_name: node-fullcycle
    entrypoint: dockerize -wait tcp://db:5432 -timeout 20s /usr/local/bin/docker-entrypoint.sh
    command: node index.js
    volumes:
      - ./node:/usr/shared/app
    networks:
      - fullcyclenet
    tty: true
    expose:
      - "3000"
    depends_on:
      - db
      - nginx

  db:
    image: postgres:16
    container_name: db-fullcycle
    restart: always
    environment:
      POSTGRES_DB: fullcycle
      POSTGRES_USER: fullcycle_user
      POSTGRES_PASSWORD: fullcycle_pass
    expose:
      - "5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - fullcyclenet

  nginx:
    build:
      context: nginx
    image: bpierrii/fullcycle-nginx
    container_name: nginx-fullcycle
    networks:
      - fullcyclenet
    ports:
      - "8080:80"

networks:
  fullcyclenet:
    driver: bridge
